services:
  db:
    image: postgres:15
    container_name: consultamed-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: consultamed
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d consultamed"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
